services:
    laravel:
        build:
            context: './backend'
            dockerfile: Dockerfile
        container_name: laravel
        ports:
          - '8000:8000'
        volumes:
            - './backend:/var/www'
        depends_on:
            - db
        networks:
            - app_network

    db:
        image: 'mysql/mysql-server:8.0'
        container_name: db
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "laravel"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "secret"
        volumes:
            - 'db_data:/var/lib/mysql'
        networks:
            - app_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            MYSQL_USERNAME: "root"
            MYSQL_ROOT_PASSWORD: "secret"
            PMA_HOST: db
        ports:
          - '8080:80'
        depends_on:
            - db
        networks:
            - app_network

    nextjs:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: nextjs
        volumes:
          - ./frontend:/app
        ports:
          - "3000:3000"
        depends_on:
          - laravel
        networks:
          - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
